const Router=require('express')
const router =new Router()
const usermiddalewaer=require('./middalewaer/user_middalewaer')
const login=require('./authlogin')
const authMusicController=require('./authMusic')
const path = require('path');
const multer=require('multer');
const cors = require("cors")
// const upload_Img_Songs=require('./middalewaer/multersongs')
const autor=require('./authautor')
const upload=require('./middalewaer/multer')
const uploadimg=require('./middalewaer/multerimg')

router.post('/musiclike',authMusicController.musicLike)
router.post('/getsongs',authMusicController.getSongs)
router.post('/creatautor',uploadimg,autor.creatAutor)
router.post('/getsongsforautor',authMusicController.get_Songs_For_autor)
router.post('/musiccreate',upload.fields([{ name: 'music1' }, { name: 'img' }]),authMusicController.musiccreate)
router.post('/music',authMusicController.getmusic)
router.post('/getmusic',authMusicController.getSearchmusic)
router.post('/test',authMusicController.test)
router.post('/register',login.register)
router.get ('/sendemail',login.sendemail)
router.post('/registercheck',login.registercheck)
router.post('/login',login.login)
router.get('/getusers',login.getusers)
router.get('/getuauthor',autor.getauthor)
router.get('/getsongsforcreatmainpage',authMusicController.get_Songs_For_Creat_Mainpage)
module.exports=router